CREATE TABLE SPRZET (
  SPRZET_ID INT PRIMARY KEY,
  OPIS varchar(80),
  TYP VARCHAR(50) NOT NULL,
  CZY_WLACZONY char check (CZY_WLACZONY in (0,1))
);

CREATE SEQUENCE sprzet_seq START WITH 1;

CREATE OR REPLACE TRIGGER sprzet_id_gen
BEFORE INSERT ON sprzet 
FOR EACH ROW
BEGIN
  SELECT sprzet_seq.NEXTVAL
  INTO   :new.sprzet_id
  FROM   dual;
END;

INSERT INTO SPRZET (OPIS, TYP, CZY_WLACZONY) VALUES ('gniazdko 1', 'gniazdko', 1);
INSERT INTO SPRZET (OPIS, TYP, CZY_WLACZONY) VALUES ('gniazdko 2', 'gniazdko', 1);

DROP TABLE POMIAR_GNIAZDKO;

CREATE TABLE POMIAR_GNIAZDKO (
  POMIAR_ID INT PRIMARY KEY,
  SPRZET_ID INT NOT NULL,
  MOMENT_POMIARU TIMESTAMP,
  POMIAR_NAPIECIE NUMBER(8,2),
  POMIAR_PRAD NUMBER(8,2),
  POMIAR_MOC NUMBER(8,2),
  CONSTRAINT FK_SPRZET
    FOREIGN KEY (SPRZET_ID) REFERENCES SPRZET(SPRZET_ID)
  );
  
CREATE SEQUENCE gniazdko_seq START WITH 1;

CREATE OR REPLACE TRIGGER gniazdko_id_gen
BEFORE INSERT ON POMIAR_GNIAZDKO
FOR EACH ROW
BEGIN
  SELECT gniazdko_seq.NEXTVAL
  INTO   :new.pomiar_id
  FROM   dual;
END;

INSERT INTO POMIAR_GNIAZDKO(SPRZET_ID, MOMENT_POMIARU, POMIAR_NAPIECIE, POMIAR_PRAD, POMIAR_MOC) VALUES (1, CURRENT_TIMESTAMP, 150.00, 31.00, 7000.00);
INSERT INTO POMIAR_GNIAZDKO(SPRZET_ID, MOMENT_POMIARU, POMIAR_NAPIECIE, POMIAR_PRAD, POMIAR_MOC) VALUES (1, CURRENT_TIMESTAMP, 152.00, 30.00, 7002.00);
INSERT INTO POMIAR_GNIAZDKO(SPRZET_ID, MOMENT_POMIARU, POMIAR_NAPIECIE, POMIAR_PRAD, POMIAR_MOC) VALUES (2, CURRENT_TIMESTAMP, 155.00, 25.00, 5002.00);
INSERT INTO POMIAR_GNIAZDKO(SPRZET_ID, MOMENT_POMIARU, POMIAR_NAPIECIE, POMIAR_PRAD, POMIAR_MOC) VALUES (2, CURRENT_TIMESTAMP, 156.00, 10.00, 4002.00);

DROP TABLE POMIAR_TEMPERATURA;

CREATE TABLE POMIAR_TEMPERATURA (
  POMIAR_ID INT PRIMARY KEY,
  SPRZET_ID INT NOT NULL,
  MOMENT_POMIARU TIMESTAMP NOT NULL,
  POMIAR_TEMP NUMBER(8,2),
  CONSTRAINT FK_SPRZET1
    FOREIGN KEY (SPRZET_ID) REFERENCES SPRZET(SPRZET_ID)
  );
  
INSERT INTO POMIAR_TEMPERATURA(SPRZET_ID, MOMENT_POMIARU, POMIAR_TEMP) VALUES (2, CURRENT_TIMESTAMP, -10);
INSERT INTO POMIAR_TEMPERATURA(SPRZET_ID, MOMENT_POMIARU, POMIAR_TEMP) VALUES (2, CURRENT_TIMESTAMP, 10);
INSERT INTO POMIAR_TEMPERATURA(SPRZET_ID, MOMENT_POMIARU, POMIAR_TEMP) VALUES (1, CURRENT_TIMESTAMP, -10);
INSERT INTO POMIAR_TEMPERATURA(SPRZET_ID, MOMENT_POMIARU, POMIAR_TEMP) VALUES (1, CURRENT_TIMESTAMP, -1);
INSERT INTO POMIAR_TEMPERATURA(SPRZET_ID, MOMENT_POMIARU, POMIAR_TEMP) VALUES (1, CURRENT_TIMESTAMP, 5);

CREATE SEQUENCE temp_seq START WITH 1;

CREATE OR REPLACE TRIGGER temp_id_gen
BEFORE INSERT ON POMIAR_TEMPERATURA 
FOR EACH ROW
BEGIN
  SELECT temp_seq.NEXTVAL
  INTO   :new.pomiar_id
  FROM   dual;
END;

SELECT S.SPRZET_ID,
  S.OPIS,
  S.CZY_WLACZONY,
  (SELECT POMIAR_TEMP FROM pomiar_temperatura POM 
  WHERE S.SPRZET_ID = POM.SPRZET_ID
    AND pom.moment_pomiaru = (SELECT MAX(POM.MOMENT_POMIARU) FROM POMIAR_TEMPERATURA POM2 WHERE POM2.sprzet_id = S.SPRZET_ID))
FROM SPRZET S;

SELECT SPRZET_ID, POMIAR_TEMP FROM pomiar_temperatura POM  
  WHERE pom.moment_pomiaru = (SELECT MAX(POM.MOMENT_POMIARU) FROM POMIAR_TEMPERATURA POM2 WHERE POM.sprzet_id = POM2.SPRZET_ID);
