/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ulka
 */
public class UrzadzeniaForm extends javax.swing.JFrame {

    /**
     * Creates new form UrzadzeniaForm
     */
    public UrzadzeniaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iconEnergy = new javax.swing.JLabel();
        iconHeating = new javax.swing.JLabel();
        iconAirCon = new javax.swing.JLabel();
        iconSolar = new javax.swing.JLabel();
        iconLighting = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salonGorneCheckBox = new javax.swing.JCheckBox();
        salonDolneCheckBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        SypGorneCheckBox = new javax.swing.JCheckBox();
        sypDolneCheckBox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        gabGorneCheckBox = new javax.swing.JCheckBox();
        gabDolneCheckBox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        dzieckaCheckBox = new javax.swing.JCheckBox();
        przedpokojCheckBox = new javax.swing.JCheckBox();
        zewnCheckBox = new javax.swing.JCheckBox();
        piwnicaCheckBox = new javax.swing.JCheckBox();
        jSliderHeating = new javax.swing.JSlider();
        jSliderAirCon = new javax.swing.JSlider();
        onOffAirCon = new javax.swing.JToggleButton();
        onOffLight = new javax.swing.JToggleButton();
        onOffHeating = new javax.swing.JToggleButton();
        onOffSolar2 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        heatingField = new javax.swing.JTextField();
        lightField = new javax.swing.JTextField();
        airConField = new javax.swing.JTextField();
        solarField = new javax.swing.JTextField();
        bilansField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Centrum sterowania");

        iconEnergy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iconEnergy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/battery.png"))); // NOI18N
        iconEnergy.setText("bilans:");

        iconHeating.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iconHeating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radiator.png"))); // NOI18N
        iconHeating.setText(" Ogrzewanie:");

        iconAirCon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iconAirCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minisplit.png"))); // NOI18N
        iconAirCon.setText(" Klimatyzacja:");

        iconSolar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iconSolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/solar-energy.png"))); // NOI18N
        iconSolar.setText("Panel słoneczny:");

        iconLighting.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iconLighting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/light-bulb.png"))); // NOI18N
        iconLighting.setText("Oświetlenie:");

        jLabel7.setText("Salon:");

        salonGorneCheckBox.setText("górne");
        salonGorneCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salonGorneCheckBoxActionPerformed(evt);
            }
        });

        salonDolneCheckBox.setText("done");

        jLabel8.setText("Sypialnia:");

        SypGorneCheckBox.setText("górne");

        sypDolneCheckBox.setText("dolne");

        jLabel9.setText("Gabinet:");

        gabGorneCheckBox.setText("górne");

        gabDolneCheckBox.setText("dolne");

        jLabel10.setText("Inne:");

        dzieckaCheckBox.setText("pokój dziecka");
        dzieckaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dzieckaCheckBoxActionPerformed(evt);
            }
        });

        przedpokojCheckBox.setText("przedpokój");
        przedpokojCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przedpokojCheckBoxActionPerformed(evt);
            }
        });

        zewnCheckBox.setText("zewnętrzne");

        piwnicaCheckBox.setText("piwnica");

        jSliderHeating.setMajorTickSpacing(1);
        jSliderHeating.setMaximum(60);
        jSliderHeating.setMinimum(40);
        jSliderHeating.setPaintLabels(true);
        jSliderHeating.setPaintTicks(true);
        jSliderHeating.setSnapToTicks(true);

        jSliderAirCon.setMajorTickSpacing(1);
        jSliderAirCon.setMaximum(30);
        jSliderAirCon.setMinimum(15);
        jSliderAirCon.setPaintLabels(true);
        jSliderAirCon.setPaintTicks(true);
        jSliderAirCon.setSnapToTicks(true);
        jSliderAirCon.setToolTipText("");
        jSliderAirCon.setValue(22);

        onOffAirCon.setText("ON / OFF");

        onOffLight.setText("ON / OFF");

        onOffHeating.setText("ON / OFF");

        onOffSolar2.setText("ON / OFF");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Aktualne zużycie / produkcja energii:");

        heatingField.setBackground(new java.awt.Color(153, 204, 255));
        heatingField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        heatingField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        heatingField.setText("- 4,5 kWh");
        heatingField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heatingFieldActionPerformed(evt);
            }
        });

        lightField.setBackground(new java.awt.Color(153, 204, 255));
        lightField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lightField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lightField.setText("- 4,5 kWh");

        airConField.setBackground(new java.awt.Color(153, 204, 255));
        airConField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        airConField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        airConField.setText("- 4,5 kWh");

        solarField.setBackground(new java.awt.Color(204, 255, 153));
        solarField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        solarField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        solarField.setText("+ 4,5 kWh");

        bilansField.setBackground(new java.awt.Color(153, 204, 255));
        bilansField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bilansField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bilansField.setText("- 9 kWh");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(iconSolar)
                                            .addComponent(iconLighting, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(onOffLight)
                                            .addComponent(onOffSolar2)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel7)
                                                .addGap(41, 41, 41))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(salonGorneCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(salonDolneCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(22, 22, 22)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SypGorneCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8)
                                            .addComponent(sypDolneCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(gabGorneCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(gabDolneCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(dzieckaCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(przedpokojCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(zewnCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(piwnicaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel10)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(iconAirCon)
                                            .addComponent(iconHeating))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(onOffAirCon)
                                            .addComponent(onOffHeating)
                                            .addComponent(jSliderAirCon, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSliderHeating, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconEnergy)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(airConField)
                            .addComponent(heatingField)
                            .addComponent(bilansField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lightField)
                            .addComponent(solarField))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(onOffHeating)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderHeating, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(heatingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(onOffAirCon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSliderAirCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(airConField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(iconAirCon))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iconSolar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(onOffSolar2)
                            .addComponent(solarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iconLighting)
                            .addComponent(onOffLight)
                            .addComponent(lightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(salonGorneCheckBox)
                                    .addComponent(SypGorneCheckBox)
                                    .addComponent(gabGorneCheckBox)
                                    .addComponent(dzieckaCheckBox)
                                    .addComponent(zewnCheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(salonDolneCheckBox)
                                    .addComponent(sypDolneCheckBox)
                                    .addComponent(gabDolneCheckBox)
                                    .addComponent(przedpokojCheckBox)
                                    .addComponent(piwnicaCheckBox)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(iconEnergy)
                                .addComponent(bilansField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(iconHeating))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void przedpokojCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przedpokojCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_przedpokojCheckBoxActionPerformed

    private void dzieckaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dzieckaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dzieckaCheckBoxActionPerformed

    private void salonGorneCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salonGorneCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salonGorneCheckBoxActionPerformed

    private void heatingFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heatingFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heatingFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrzadzeniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrzadzeniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrzadzeniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrzadzeniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UrzadzeniaForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox SypGorneCheckBox;
    private javax.swing.JTextField airConField;
    private javax.swing.JTextField bilansField;
    private javax.swing.JCheckBox dzieckaCheckBox;
    private javax.swing.JCheckBox gabDolneCheckBox;
    private javax.swing.JCheckBox gabGorneCheckBox;
    private javax.swing.JTextField heatingField;
    private javax.swing.JLabel iconAirCon;
    private javax.swing.JLabel iconEnergy;
    private javax.swing.JLabel iconHeating;
    private javax.swing.JLabel iconLighting;
    private javax.swing.JLabel iconSolar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSliderAirCon;
    private javax.swing.JSlider jSliderHeating;
    private javax.swing.JTextField lightField;
    private javax.swing.JToggleButton onOffAirCon;
    private javax.swing.JToggleButton onOffHeating;
    private javax.swing.JToggleButton onOffLight;
    private javax.swing.JToggleButton onOffSolar2;
    private javax.swing.JCheckBox piwnicaCheckBox;
    private javax.swing.JCheckBox przedpokojCheckBox;
    private javax.swing.JCheckBox salonDolneCheckBox;
    private javax.swing.JCheckBox salonGorneCheckBox;
    private javax.swing.JTextField solarField;
    private javax.swing.JCheckBox sypDolneCheckBox;
    private javax.swing.JCheckBox zewnCheckBox;
    // End of variables declaration//GEN-END:variables
}
